name: 💬 Feedback & Questions
description: Share general feedback, questions, or workflow ideas.
title: "[FEEDBACK]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        We love hearing your thoughts and feedback! Share your feedback or questions below.
  - type: textarea
    id: feedback
    attributes:
      label: Feedback / Question
      description: What is on your mind?
      placeholder: I love using Edge-Drop because... It would be even better if...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Notes
      description: Any other details you'd like to share.
